<a href="https://colab.research.google.com/github/jsdysw/knn-classifier/blob/master/k_nn_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataset analysis
feature vector X = {f1, f2, f3, f4, f5, f6}

class vector C = {"satisfied", "unsatisfied"}

In [101]:
import pandas as pd
import os

# load satisfaction_data.csv from the github repository

# url = 'https://raw.githubusercontent.com/jsdysw/knn-classifier/master/satisfaction_data.csv?token=GHSAT0AAAAAABQYSI53RANCS5CDDMW3Y3OIYTRKKOQ'
# df = pd.read_csv(url, header=None)

directory_data = './'
filename_data = 'satisfaction_data.csv'
df = pd.read_csv(os.path.join(directory_data, filename_data), header=None)
dataset = df.to_numpy() # pandas dataframe -> numpy

print("Examples of dataset : \n", dataset[0:3])

# split data into train_data(9) and test_data(1)
train_data = dataset[0:18000]
test_data = dataset[18000:]

# split into features and class
X_train = train_data[:,:6]
y_train = train_data[:,6]
X_test = test_data[:,:6]
y_test = test_data[:,6]

print("\nShape of X_train : ", X_train.shape)
print("Shape of y_train : ", y_train.shape)
print("X_train example : \n", X_train[0:2])
print("y_train example : \n", y_train[0:2])

print("\nShape of X_test : ", X_test.shape)
print("Shape of y_test : ", y_test.shape)
print("X_test example : \n", X_test[0:2])
print("y_test example : \n", y_test[0:2])


Examples of dataset : 
 [[40 2 1 86872 25 9 'unsatisfied']
 [40 2 1 259323 54 10 'satisfied']
 [40 2 1 256813 43 14 'satisfied']]

Shape of X_train :  (18000, 6)
Shape of y_train :  (18000,)
X_train example : 
 [[40 2 1 86872 25 9]
 [40 2 1 259323 54 10]]
y_train example : 
 ['unsatisfied' 'satisfied']

Shape of X_test :  (2000, 6)
Shape of y_test :  (2000,)
X_test example : 
 [[33 1 0 46094 42 13]
 [50 4 1 140319 57 9]]
y_test example : 
 ['unsatisfied' 'unsatisfied']


# Distance
the difference between two data is defined as L2 norm

In [97]:
import numpy as np

def get_distance(data1, data2) :
    diff = data1 - data2
    l2_norm = np.sum(np.square(diff)) ** 0.5
    # print("data1 : ", data1)
    # print("data2 : ", data2)
    # print("diff : ", np.square(diff))
    # print(l2_norm)
    return l2_norm

# get_distance(X_test[0], X_test[1])

# k-NN model